### PR TITLE
添加测试数据(不知道算不算脱敏了),  添加bearer token认证;

### PR DESCRIPTION
**Pull request by JamesBonddu**
- add test data reference from WUHAN2020 shimo readme link, remove sensitive information except logistical.

- update csv to json, but left some keys need translate chinese into english.

- change auth_check loc use Bearer token.

- auth_token temporary use test, .gitignore to protect product token.

- test sample
```sh
curl --location --request GET '127.0.0.1:9000/wuhan2020/hotel_list' \
--header 'Authorization: Bearer test-safe-wuhan'
```

### Purpose | 本PR解决的问题

- Closes #

### Changes | 本PR的更改

- No changes.

### CODE REVIEW

**Comment by daca-ao** [comment]
Good to see .csv files here.

**Comment by daca-ao** [comment]
Please do an update in README as well.

**Review by rexwangcc — APPROVED** [review]
LGTM. Love the usage of `current_app` as well as having AuthN.

**Comment by JamesBonddu** [comment]
> Please do an update in README as well.

ok

**Pull request merged**
