### PR TITLE
Update repo to use python 3.6.10

### PR DESCRIPTION
**Pull request by chenrui333**
### Purpose | 本PR解决的问题
Kind of related to #28 

- Closes #

### Changes | 本PR的更改

Update repo python version to 3.8

### CODE REVIEW

**Review by rexwangcc — APPROVED** [review]
LGTM, while I agree with using Py3.x everywhere, I'm not sure if Py3.8 is supported by the current deployment to aliyun. @LiuChangFreeman  Could you answer this? If it's not supported, we could keep Py3.7, since there are only a few new changes in 3.8 from 3.7 (e.g. the walrus operator, etc.)

**Comment by chenrui333** [comment]
yeah, agree. How does the deployment model look like?

**Comment by rexwangcc** [comment]
As far as I can tell, it's deployed as a serverless app on Function Compute (which looks similar to Cloud Functions or Lambda Functions), but I could be wrong.

**Comment by chenrui333** [comment]
阿里云好像只用3.6, :sad:

Last Updated: Aug 21, 2019
Function Compute currently supports the following Python runtime environments:

- Python 2.7 with runtime version 2.7
- Python 3.6 with runtime version 3

Pretty far behind AWS.

**Comment by chenrui333** [comment]
如果要deploy 到 阿里云上面 我可以帮忙做 infra as code.

**Comment by rexwangcc** [comment]
如果您是指类似Terraform 之类的，我觉得目前的codebase还没有这个需求，并且代码也没有稳定到需要很成熟的DevOps。不介意的话您可以提交一个issue来记录这个想法。

此外，不介意的话，请您将PR中的版本改为Py3.6 :octocat:

**Comment by LiuChangFreeman** [comment]
仅限于python3.6的特性

**Comment by chenrui333** [comment]
没问题 我马上改成 python 3.6

**Comment by chenrui333** [comment]
application 端 不一定要用 terraform, 可以用 serverless

**Review by rexwangcc — APPROVED** [review]
Thanks and LGTM, `docker run -it aliyunfc/runtime-python3.6:build python` tells `3.6.3`, so there might be some minor tweaks with the deployment.

**Pull request merged**
